<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test suite"
           tests="3"
           failures="1"
           errors="0"
           skipped="2"
           time="0.007">
    <properties></properties>

            <testcase
                name="setUpBrowser"
                time="0.007"
                classname="testcases.AppleTest">

            <failure type="java.lang.NullPointerException" message="(null)">
                <![CDATA[java.lang.NullPointerException
                library.SelectBrowser.StartBrowser(SelectBrowser.java:35)testcases.AppleTest.setUpBrowser(AppleTest.java:51)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:498)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)org.testng.TestRunner.beforeRun(TestRunner.java:529)org.testng.TestRunner.run(TestRunner.java:497)org.testng.SuiteRunner.runTest(SuiteRunner.java:455)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)org.testng.SuiteRunner.run(SuiteRunner.java:364)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)org.testng.TestNG.runSuitesLocally(TestNG.java:1137)org.testng.TestNG.runSuites(TestNG.java:1049)org.testng.TestNG.run(TestNG.java:1017)org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </failure>
    </testcase>

            <testcase
                name="click_on_bag_test"
                time="0.0"
                classname="testcases.AppleTest">
            </testcase>
            <testcase
                name="login_into_account_with_wrong_password_test"
                time="0.0"
                classname="testcases.AppleTest">
            </testcase>

</testsuite>
